# A stable environment for ML, PyTorch, and Sentence-Transformers
name: ml_env
channels:
  - pytorch
  - nvidia     # For the CUDA toolkit
  - conda-forge
  - defaults
dependencies:
  # --- Core & Stable Python ---
  # This is the main fix for your 'gemma3_text' error
  - python=3.10
  - pip

  # --- Core Data Science Libs ---
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - jupyterlab
  - matplotlib
  - seaborn
  - tqdm
  - scikit-image

  # --- Pip for specialized packages ---
  # sentence-transformers is best installed via pip
  - pip:
    - sentence-transformers
    - transformers
    - plotly
    - xgboost
    - lightgbm
    - catboost
    - shap
